name: Android CI
on:
  push: { branches: [ main ] }
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - name: Install SDK
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.2"
          yes | sdkmanager --licenses
      - name: Build
        shell: bash
        run: |
          set -o pipefail
          chmod +x gradlew
          ./gradlew clean :app:assembleDebug --no-daemon --stacktrace 2>&1 | tee gradle-build.log
      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: gradle-build.log
      - name: Upload outputs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: app/build/outputs/**
