name: Android CI
on:
  push:
    branches: [ main ]
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "build-tools;34.0.2"
          yes | sdkmanager --licenses
          sdkmanager --list | head -n 200

      - name: Ensure Gradle wrapper exists
        run: test -f gradlew || { echo "Gradle wrapper missing"; exit 1; }
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Print tool versions
        run: ./gradlew -v

      - name: Build Debug APK (capture stdout+stderr)
        shell: bash
        run: |
          set -o pipefail
          ./gradlew clean :app:assembleDebug --no-daemon --stacktrace --warning-mode all 2>&1 | tee gradle-build.log

      - name: List build outputs
        run: |
          echo "::group::outputs"
          ls -R app/build/outputs || true
          echo "::endgroup::"
          find app -type f \( -name "*debug*.apk" -o -name "*.aab" \) -print || true

      - name: Upload build logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: gradle-build.log

      - name: Upload build outputs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: app/build/outputs/**
