name: Android CI
on:
  push: { branches: [ main ] }
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      # Generate/commit the Gradle wrapper locally first (Android Studio or ./gradlew wrapper)
      - name: Build debug
        run: ./gradlew :app:assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: installerapp-debug-apk
          path: app/build/outputs/apk/debug/*.apk
