name: Android CI
on:
  push:
    branches: [ main ]
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Ensure Gradle wrapper exists
        run: test -f gradlew || { echo "Gradle wrapper missing"; exit 1; }
      
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Print Gradle/Java versions
        run: ./gradlew -v

      - name: Build Debug APK (capture logs)
        run: ./gradlew clean :app:assembleDebug --no-daemon --stacktrace --warning-mode all | tee gradle-build.log

      - name: Upload build logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            gradle-build.log
            **/build/reports/**
            **/outputs/logs/**

      - name: Upload APK artifact (on success)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: installerapp-debug-apk
          path: app/build/outputs/apk/debug/*.apk
